apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-portal
  labels:
    app: employee-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-portal
  template:
    metadata:
      labels:
        app: employee-portal
    spec:
      containers:
        - name: employee-portal
          image: vivek8341/employee-portal:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "False"
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
